# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-21 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(max_length=100, unique=True)),
                ('track_genre', models.CharField(max_length=30, unique=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('track_rating', models.IntegerField(default=5)),
            ],
        ),
    ]
